remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme 

title: binslashmimi.log
tagline: "Breaking, building, reporting, learning."
description: "A personal blog and notes site by Mimi, cybersecurity analyst and aspiring pentester. Sharing ethical hacking writeups, tools, learning reflections, and experiments"
